name: Check Schema Changes

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  check_schema:
    name: Detect schema changes
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install gql and httpx
        run: |
          python -m pip install --upgrade pip
          pip install "gql[httpx]==3.6.0b4"
      - name: Download latest schema
        env:
          GPP_URL: ${{ secrets.GPP_URL }}
          GPP_TOKEN: ${{ secrets.GPP_TOKEN }}
        run: |
          python scripts/download_schema.py
      - name: Check for schema drift
        run: |
          git diff --exit-code schema.graphql
