name: Run Lint and Tests

on:
  pull_request:
    branches: [main]
    paths:
      - "src/**/*.py"
      - "tests/**/*.py"
      - "pyproject.toml"
  push:
    branches: [main]

jobs:
  run_linter:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Nox
        run: |
          python -m pip install --upgrade pip
          python -m pip install nox

      - name: Run Nox github_lint session
        run: nox --force-color -s github_lint

  run_tests:
    needs: run_linter
    runs-on: [ubuntu-latest]
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Nox
        run: |
          python -m pip install --upgrade pip
          python -m pip install nox

      - name: Run Nox github_tests session
        run: nox --force-color --python ${{ matrix.python-version }} -s github_tests

      # - name: Upload coverage to Codecov
      #   if: matrix.python-version == '3.10'
      #   uses: codecov/codecov-action@v5
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
